# Generated by Django 4.1.7 on 2023-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_rename_studenstrack_student_studentstrack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trackcourses',
        ),
        migrations.AddField(
            model_name='track',
            name='courses',
            field=models.ManyToManyField(to='iot.course'),
        ),
    ]
