# Generated by Django 4.1.7 on 2023-04-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_student_studentscourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
